title: "Carlos Reynaldo Portocarrero Tovar, Ph.D."
theme: jekyll-theme-minimal
markdown: GFM
description: "Computational Neuroscience • Boolean Networks • HPC"
show_downloads: false
theme: jekyll-theme-minimal

# Opcional: enlaces sociales
github:
  username: crtpcusco
linkedin: "https://www.linkedin.com/in/tu-perfil"
orcid: "https://orcid.org/0000-0002-3924-8367"
scopus: "https://www.scopus.com/authid/detail.uri?authorId=57215312322"
